security:
  encoders:
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: app_user_provider
      logout:
        path: app_logout
      remember_me:
        secret: '%kernel.secret%'
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
  access_control:
    - { path: '^/[a-z]{2}/admin', roles: ROLE_ADMIN }
    - { path: '^/[a-z]{2}/admin/users', roles: ROLE_ADMIN }
    - { path: '^/[a-z]{2}/gallery', roles: ROLE_USER }
    - { path: '^/[a-z]{2}/profile', roles: ROLE_USER }
    - { path: '^/api/delete_profile_image', roles: ROLE_ADMIN }
    - { path: '^/api/delete_user', roles: ROLE_ADMIN }
    - { path: '^/api/gallery_paging', roles: ROLE_USER }
    - { path: '^/api/update_roles', roles: ROLE_ADMIN }
    - { path: '^/api/upload_images', roles: ROLE_USER }
