security:
  encoders:
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: app_user_provider
      logout:
        path: app_logout
      remember_me:
        secret: '%kernel.secret%'
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
  access_control:
    - { path: '^/[a-z]{2}/admin', roles: ROLE_ADMIN }
    - { path: '^/[a-z]{2}/admin/news', roles: ROLE_ADMIN }
    - { path: '^/[a-z]{2}/admin/users', roles: ROLE_ADMIN }
    - { path: '^/[a-z]{2}/gallery', roles: ROLE_USER }
    - { path: '^/[a-z]{2}/news', roles: ROLE_USER }
    - { path: '^/[a-z]{2}/profile', roles: ROLE_USER }
    - { path: '^/api/delete-news-article', roles: ROLE_ADMIN }
    - { path: '^/api/delete-profile-image', roles: ROLE_ADMIN }
    - { path: '^/api/delete-user', roles: ROLE_ADMIN }
    - { path: '^/api/edit-news-article', roles: ROLE_ADMIN }
    - { path: '^/[a-z]{2}/api/gallery-paging', roles: ROLE_USER }
    - { path: '^/[a-z]{2}/api/news-paging', roles: ROLE_USER }
    - { path: '^/api/update-roles', roles: ROLE_ADMIN }
    - { path: '^/api/upload-assets', roles: ROLE_USER }
