app_admin:
  path: /{_locale}/admin
  controller: App\Controller\AdminController::adminAction
  options:
    navigation: main
    order: 4
    role: ROLE_ADMIN
    subpages:
      - app_admin_users
      - app_admin_news

app_admin_news:
  path: /{_locale}/admin/news
  controller: App\Controller\AdminController::newsAction
  options:
    navigation: admin
    order: 2
    role: ROLE_ADMIN

app_admin_users:
  path: /{_locale}/admin/users
  controller: App\Controller\AdminController::usersAction
  options:
    navigation: admin
    order: 1
    role: ROLE_ADMIN
