app_admin:
  path: /admin
  controller: App\Controller\AdminController::adminAction

app_index:
  path: /
  controller: App\Controller\DefaultController::indexAction

app_login:
  path: /login
  controller: App\Controller\SecurityController::loginAction

app_logout:
  path: /logout

app_profile:
  path: /profile
  controller: App\Controller\DefaultController::profileAction

app_register:
  path: /register
  controller: App\Controller\SecurityController::registerAction
