imports:
  - { resource: parameters.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    public: true

  App\Controller\GalleryController:
    class: App\Controller\GalleryController
    calls:
      - ['setUploadDirectory', ['%upload_directory%']]

  App\Controller\ProfileController:
    class: App\Controller\ProfileController
    calls:
      - ['setUploadDirectory', ['%upload_directory%']]

  App\Service\FileService:
    class: App\Service\FileService
    calls:
      - ['setUploadDirectory', ['%upload_directory%']]

  App\Service\HashService:
    class: App\Service\HashService
    arguments:
      - '%hashids_salt%'
      - '%hashids_padding%'

  Liip\ImagineBundle\Service\FilterService:
    alias: liip_imagine.service.filter
