parameters:
  hashids_salt: k8rourn0zwJgPJISnmS1
  hashids_padding: 8

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Service\HashService:
      class: App\Service\HashService
      arguments:
        - '%hashids_salt%'
        - '%hashids_padding%'
