imports:
  - { resource: parameters.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Controller\GalleryController:
    class: App\Controller\GalleryController
    arguments:
      - '%upload_directory%'

  App\Controller\ProfileController:
    class: App\Controller\ProfileController
    arguments:
      - '%upload_directory%'

  App\Service\FileService:
    class: App\Service\FileService
    arguments:
      - '%upload_directory%'

  App\Service\HashService:
    class: App\Service\HashService
    arguments:
      - '%hashids_salt%'
      - '%hashids_padding%'
