parameters:
  hashids_salt: '%env(string:HASHIDS_SALT)%'
  hashids_padding: '%env(string:HASHIDS_PADDING)%'
  upload_directory: '%env(string:UPLOAD_DIRECTORY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    public: true

  App\Controller\GalleryController:
    class: App\Controller\GalleryController
    calls:
      - ['setUploadDirectory', ['%upload_directory%']]

  App\Controller\ProfileController:
    class: App\Controller\ProfileController
    calls:
      - ['setUploadDirectory', ['%upload_directory%']]

  App\Service\FileService:
    class: App\Service\FileService
    calls:
      - ['setUploadDirectory', ['%upload_directory%']]

  App\Service\HashService:
    class: App\Service\HashService
    arguments:
      - '%hashids_salt%'
      - '%hashids_padding%'

  App\Twig\HelperExtension:
    class: App\Twig\HelperExtension
    arguments:
      - '%kernel.environment%'

  Liip\ImagineBundle\Service\FilterService:
    alias: liip_imagine.service.filter
